### ISSUE TITLE
jQuery 1.5.2 issues

### ISSUE THREAD

**Issue by dallasbpeters** [cdwharton/BugMeBar#2]
Hey awesome stuff with BugMeBar!! 

I'm running into issues with jQuery 1.5.2. Probably not possible to upgrade right now, but do you have any ideas on how to make it a bit more backwards compatible?

**Comment by cdwharton** [comment]
Thanks, no plans to go back down to 1.5.2 I'm afraid. Feel free to rework it yourself if you need to go back that far.
